"""
Markdown Digest Renderer
記事データを Markdown 形式のダイジェストとして出力。
"""

from dataclasses import dataclass
from datetime import datetime


@dataclass
class DigestArticle:
    title: str
    source: str
    url: str
    summary: str
    category: str
    relevance_tag: str  # 転用示唆: 本業/個人開発/農業
    is_starred: bool


def render_digest(
    articles_by_category: dict[str, list[DigestArticle]],
    generated_at: datetime,
    lookback_hours: int,
) -> str:
    """Markdown ダイジェストを生成。"""
    lines: list[str] = []

    # Header
    date_str = generated_at.strftime("%Y-%m-%d")
    time_str = generated_at.strftime("%H:%M JST")
    lines.append(f"# Daily Digest - {date_str}")
    lines.append("")
    lines.append(f"**生成時刻:** {time_str}")
    lines.append(f"**対象範囲:** 過去 {lookback_hours} 時間")
    total = sum(len(arts) for arts in articles_by_category.values())
    lines.append(f"**記事数:** {total} 件")
    lines.append("")
    lines.append("---")
    lines.append("")

    # カテゴリ別表示順
    category_labels = {
        "AI_RESEARCH": "AI Research",
        "AI_PRODUCT_SAAS": "AI Product / SaaS",
        "MACRO_STRUCTURE": "Macro & Structure",
        "JAPAN_SIGNAL": "Japan Signal",
        "AGRICULTURE": "Agriculture",
    }

    for cat_key, cat_label in category_labels.items():
        articles = articles_by_category.get(cat_key, [])
        if not articles:
            continue

        lines.append(f"## {cat_label}")
        lines.append("")

        for i, art in enumerate(articles, 1):
            star = " ⭐" if art.is_starred else ""
            lines.append(f"### {i}. {art.title}{star}")
            lines.append(f"**出典:** {art.source} | [記事リンク]({art.url})")
            lines.append("")
            lines.append(f"> {art.summary}")
            lines.append("")
            if art.relevance_tag:
                lines.append(f"**転用示唆:** {art.relevance_tag}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.append(f"*Generated by digest-generator at {time_str}*")
    lines.append("")

    return "\n".join(lines)
